name: Link Checker 

on:
  workflow_dispatch: 
    inputs:
      deployment:
        description: 'Select the deployment to check links in'
        required: true
        default: 'mi.docs.wso2.com/en/latest'
        type: choice
        options:
        - mi.docs.wso2.com/en/latest

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
    - name: Run link checker
      env:
        DEPLOYMENT: ${{ inputs.deployment }}
      run: |
        npm install --global @deptagency/octopus@latest
        
        URL=https://$DEPLOYMENT/
        echo "Checking links in $URL"
        octopus $URL

        # Run octopus and catch errors for better logging
        #set -e
        #{
        #  octopus $URL
        #} || {
        #  echo "Error occurred while running octopus"
        #  echo "Debugging info: URL=$URL, Deployment=$DEPLOYMENT"
        #  exit 1
        #}
